include drivers/InfotmMedia/env.mk

#obj-$(CONFIG_CAM_GT0308) += gc0308_xyc.o
#obj-$(CONFIG_CAM_GT2005) += gt2005_xyc.o
#obj-y += gc0307_aih.o
#obj-y += gc0308_demo.o
#obj-y += gc0308_demo_130w.o
obj-y += gc0308_xyc.o
#obj-y += gc0308_hy.o
#obj-y += gc0308_hy_suoku.o
#obj-y += gc0308_hy_130w.o
#obj-y += gc0308_fyf.o
#obj-y += gc0308_130w.o
#obj-y += gc0308_w2.o
#obj-y += gc0308_zyhb.o
#obj-y += gc0309_zyhb.o
#obj-y += gc2015_zyhb.o
#obj-y += gc2035_demo.o
#obj-y += gc2035_demo_500w.o
#obj-y += gt2005_demo.o
#obj-y += gt2005_xyc.o
#obj-y += gt2005_pc0am0008a.o
#obj-y += gt2005_pc0am0004b.o
#obj-y += gt2005_zyhb.o
#obj-y += gt2005_500w.o
#obj-y += hi253_yuv.o
#obj-y += hi253_hy.o
#obj-y += hi704_yuv.o
#obj-y += hi704_hy.o
#obj-y += hi704_gaof.o
#obj-y += ov5640_zyhb.o
#obj-y += ov5650_p48a.o
#obj-y += ov5650_mipi.o
#obj-y += ov5642_demo.o
#obj-y += gc2035_gsg.o
#obj-y += sp0838_zyhb.o
#obj-y += sp2518_demo.o
#obj-y += sp0838_130w.o
obj-y += sp2518_500w.o
#obj-y += ov5640_fxn.o
#obj-y += mt9m114_demo.o
#obj-y += mt9d115_demo.o


EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/csi_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/csi_lib_i800/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camsen_lib/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camsen_lib/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camif_lib_i800/include

#EXTRA_CFLAGS += -DIM_DEBUG
