#
# Makefile InfotmMedia G2D i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += csi_pwl_linux.o
obj-y += csi_driver.o
obj-y += csi_api.o
obj-y += csi_lib.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/csi_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/csi_lib_i800/source

#EXTRA_CFLAGS += -DIM_DEBUG

