#
# Makefile of memalloc.
#
# Sololz <sololz.luo@gmail.com>.
#

obj-$(CONFIG_IMAP_MEMALLOC) += memalloc.o
obj-$(CONFIG_IMAP_SHARED_MEMORY_SUPPORT) += shm_so.o
obj-$(CONFIG_MEMORY_ALLOCATOR_WITH_NO_EXT_FRAGMENT) += mmalcr/
