#
# Makefile InfotmMeida pmm i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#


include drivers/InfotmMedia/env.mk
obj-y += dmmu_lib.o
obj-y += dmmu_pwl_linux.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dmmu_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dmmu_lib_i800/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/pmm_lib/include

#EXTRA_CFLAGS += -DIM_DEBUG

