#
# Makefile InfotmMedia G2D i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += isp_acc.o
obj-y += isp_acm.o
obj-y += isp_ae.o
obj-y += isp_af.o
obj-y += isp_awb.o
obj-y += isp_bccb.o
obj-y += isp_bdc.o
obj-y += isp_cmncsc.o
obj-y += isp_crop.o
obj-y += isp_ee.o
obj-y += isp_fcc.o
obj-y += isp_gma.o
obj-y += isp_hist.o
obj-y += isp_ief.o
obj-y += isp_lens.o
obj-y += isp_lib.o
obj-y += isp_osd.o
obj-y += isp_scl.o
obj-y += isp_pwl_linux.o
obj-y += isp_reg_drv.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/isp_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/isp_lib_i800/source

#EXTRA_CFLAGS += -DIM_DEBUG

