#
# Makefile InfotmMeida ids i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += lcd_lib.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_lib_i800/source
EXTRA_CFLAGS += -Idrivers/emif

#EXTRA_CFLAGS += -DIM_DEBUG

