#
# Makefile InfotmMeida ids i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += lcd_api.o
#obj-y += lcd_HSD070IDW1_800x480.o
obj-y += lcd_CLAP070NJ02CW_1024x600.o
#obj-y += lcd_BF097XN_1024x768.o
#obj-y += lcd_BF097XN01_1024x768.o
#obj-y += lcd_LXJC070NDM350_18C2_800x480.o
#obj-y += lcd_T70P03_1024x600.o
#obj-y += lcd_W2_1024x600.o
#obj-y += lcd_M710C_1024x600.o
#obj-y += lcd_TM097TDH01_1024x768.o
#obj-y += lcd_LY7060BD_800x480.o
#obj-y += lcd_CRD080TN01_1024x768.o
#obj-y += lcd_T070SWS057H_1024x600.o
#obj-y += lcd_RS3WSN70040A_1024x600.o
#obj-y += lcd_RS3WSN70040A_BiNai_1024x600.o
#obj-y += lcd_CLAA070WP03XG_1024x600.o
#obj-y += lcd_KR080PC1S_800x600.o
#obj-y += lcd_SHUOYING_N1066_1024X600.o
#obj-y += lcd_KR070PA6S_800x480.o
#obj-y += lcd_HSD101_1280x800.o
#obj-y += lcd_HSD101PWW1_1280x800.o
#obj-y += lcd_TM097TDH01V2_1024x768.o
#obj-y += lcd_SL008DC21B01_800x600.o
#obj-y += lcd_SL008DH24B01_1024x768.o
#obj-y += lcd_LP133WH2_1366x768.o
obj-y += lcd_AT070TN93V2_800x480.o
obj-y += lcd_KX0705001A0_800x480.o


EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_api/source


#EXTRA_CFLAGS += -DIM_DEBUG

