#
# Makefile InfotmMedia G2D i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += g2d_kui.o
obj-y += g2d_lib.o
obj-y += g2d_sclee.o
obj-y += g2d_dith.o
obj-y += g2d_reg_drv.o
obj-y += wq.o
obj-y += g2d_pwl_linux.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/pmm_lib/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/g2d_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/g2d_lib_i800/source

#EXTRA_CFLAGS += -DIM_DEBUG

