#
# Makefile InfotmMeida ids i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/hdmi_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/hdmi_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/hdmi_lib_i800/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/include

#EXTRA_CFLAGS += -DIM_DEBUG


obj-y += hdmi_lib.o
obj-y += api.o

obj-y += access.o
obj-y += board.o
obj-y += hdmi_system.o
obj-y += mutex.o

obj-y += audio.o
obj-y += audioParams.o
obj-y += control.o
obj-y += halAudioClock.o
obj-y += halAudioGenerator.o
obj-y += halAudioGpa.o
obj-y += halAudioHbr.o
obj-y += halAudioI2s.o
obj-y += halAudioSpdif.o
obj-y += halColorSpaceConverter.o
obj-y += halFrameComposerAcp.o
obj-y += halFrameComposerAudio.o
obj-y += halFrameComposerAudioInfo.o
obj-y += halFrameComposerAvi.o
obj-y += halFrameComposerDebug.o
obj-y += halFrameComposerGamut.o
obj-y += halFrameComposerGcp.o
obj-y += halFrameComposerIsrc.o
obj-y += halFrameComposerPackets.o
obj-y += halFrameComposerSpd.o
obj-y += halFrameComposerVideo.o
obj-y += halFrameComposerVsd.o
obj-y += halIdentification.o
obj-y += halInterrupt.o
obj-y += halMainController.o
obj-y += halVideoGenerator.o
obj-y += halVideoPacketizer.o
obj-y += halVideoSampler.o
obj-y += packets.o
obj-y += productParams.o
obj-y += video.o
obj-y += videoParams.o

obj-y += colorimetryDataBlock.o
obj-y += dtd.o
obj-y += edid.o
obj-y += halEdid.o
obj-y += hdmivsdb.o
obj-y += monitorRangeLimits.o
obj-y += shortAudioDesc.o
obj-y += shortVideoDesc.o
obj-y += speakerAllocationDataBlock.o
obj-y += videoCapabilityDataBlock.o

obj-y += halHdcp.o
obj-y += hdcp.o
obj-y += hdcpParams.o
obj-y += hdcpVerify.o

obj-y += halI2cMasterPhy.o
obj-y += halSourcePhy.o
obj-y += phy.o

obj-y += bitOperation.o
obj-y += error.o
obj-y += hdmi_log.o



