#
# Makefile InfotmMedia ISP i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += camsen_lib.o
obj-y += camsen_pwl_linux.o
obj-y += camsen_utils.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camsen_lib/include

#EXTRA_CFLAGS += -DIM_DEBUG

