#
# Makefile InfotmMedia G2D i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk

obj-y += camisp_api.o
obj-y += isp_sen.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/isp_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/isp_lib_i800/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camsen_lib/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camisp_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/camisp_api/source

#EXTRA_CFLAGS += -DIM_DEBUG

