#
# linux/drivers/nand/Makefile
#

obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_mtd.o
obj-$(CONFIG_MTD_INFOTM_NAND)	+= imapx800.o
obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_ids.o
obj-$(CONFIG_MTD_INFOTM_NAND)	+= part.o
obj-$(CONFIG_MTD_INFOTM_NAND)	+= rtc_reboot.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_bbt.o

