# arch/arm/plat-imap/Makefile
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
# Licensed under GPLv2


obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=


# Core files
obj-y				+= clock.o
obj-y				+= mem_reserve.o
# Architecture dependant builds

