#
# Makefile InfotmMeida ids i800 driver.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/InfotmMedia/env.mk
obj-y += dsi_lib.o
obj-y += mipi_dsih_hal.o
obj-y += mipi_dsih_api.o
obj-y += mipi_dsih_dphy.o
obj-y += mipi_dsih_hal.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_lib_i800/source

#EXTRA_CFLAGS += -DIM_DEBUG




