#
## Makefile for the HDMI output interface driver
#

obj-$(CONFIG_HDMI_SI9022) += sii9022.o SIIAV_Config.o SIIEDID.o SIIHDCP.o SIISiI9022A72.o SIITPI_Access.o	 \
		 SIITPI.o SIIVideoModeTable.o Globals.o

