#
# Makefile InfotmMeida ids i800 driver.
#
# Copyright (c) 2009~2014 ShangHai InfoTM Ltd all rights reserved.
#
#

# mipidsi 
include drivers/InfotmMedia/env.mk
obj-y += dsi_api.o
obj-y += dpi_VVX10F004B00_1920x1200.o

EXTRA_CFLAGS += -Idrivers/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_api/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/dsi_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/ids_lib_i800/source
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_lib_i800/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/lcd_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/i80_api/include
EXTRA_CFLAGS += -Idrivers/InfotmMedia/i80_lib_i800/include

#EXTRA_CFLAGS += -DIM_DEBUG
